name: Docker Image CI

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -  
        name: connect ssh
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop miniyusuf
            docker rm miniyusuf
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/miproyusuf
            docker run --name miniyusuf -p 8080:8080 -d \
              -e DBHOST=${{secrets.HOST}} \
              -e DBPORT=3306 \
              -e DBUSER=${{secrets.DBUSER}} \
              -e DBNAME=${{secrets.DBNAME}} \
              -e DBPASS=${{secrets.DBPASS}} \
              -e SECRET=${{secrets.SECRET}} \
              -e CLIENT_EMAIL=${{secrets.EMAIL}} \
              -e PRIVATE_KEY=${{ secrets.PRIVATE }} \ # Use the secret here
              -e FOLDER_ID=${{secrets.FOLDER}} \
              -e OPENAI_KEY=${{secrets.OPENAI}} \
              ${{ secrets.DOCKERHUB_USERNAME }}/miproyusuf
